### ISSUE TITLE
galp3-b Thunderbolt does not work

### ISSUE THREAD

**Issue by ahoneybun** [system76/coreboot#1]
GNOME Settings shows that TBT is either disabled in the BIOS or has the incorrect security level. 

Pop 18.10 Intel image 
Latest SeaBIOS as of today.

**Comment by ahoneybun** [comment]
Screenshot of GNOME Control Center
![screenshot from 2019-02-13 10-40-15](https://user-images.githubusercontent.com/4884946/52732078-84aea900-2f7c-11e9-98be-0352979af5bc.png)

**Comment by curiousercreative** [comment]
@ahoneybun was this issue never resolved?

**Comment by jackpot51** [comment]
Due to this issue and others with the galp3-b, we are not planning to support the galp2, galp3, or galp3-b. We are planning to support the galp3-c at some time.

**Comment by curiousercreative** [comment]
@jackpot51 perhaps the issue should be closed then? I've ordered my first system76 computer, a galp5, but not before browsing the repos and going through issues and pull requests. The fewer long standing issues, the more confidence I have generally. I'm glad to see some galp5 ec merged just today and hopeful that my new laptop will be supported well into the future :)

**Comment by jackpot51** [comment]
Obviously any product that is sold with coreboot will be supported with it indefinitely
