### ISSUE TITLE
Failing to clone due to missing 3rd-party commit

### ISSUE THREAD

**Issue by jacobgkau** [system76/coreboot#130]
Getting this error when running `update.sh` in firmware-open:

```
jacob@serw12:~/Work/firmware-open$ ./scripts/update.sh 
Already up to date.
fatal: remote error: want 6c0c4691e5bb446e0e428ebca595164709c59586 not valid
fatal: Fetched in submodule path 'coreboot/3rdparty/intel-microcode', but it did not contain 6c0c4691e5bb446e0e428ebca595164709c59586. Direct fetching of that commit failed.
fatal: 
fatal: Failed to recurse into submodule path 'coreboot'
```

Happens whether I clone via `git://` or `https://`.

**Comment by jacobgkau** [comment]
`update.sh` apparently isn't needed, and this doesn't happen when running `deps.sh`.

**Comment by crawfxrd** [comment]
Intel rewrote the commit history. The commit no longer exists.

**Comment by crawfxrd** [comment]
Fixed by [CB:66581](https://review.coreboot.org/c/coreboot/+/66581).

I've cherry-picked it to the `system76` branch.
