### ISSUE TITLE
galp3-b Webcam does not work

### ISSUE THREAD

**Issue by ahoneybun** [system76/coreboot#2]
I'm not able to enable the webcam with F10 or the hardware does not see the webcam. It is not listed in 'lsusb'.

aaronhoneycutt@pop-os ~/g/fresh-install-script> lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 8087:0a2b Intel Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
aaronhoneycutt@pop-os ~/g/fresh-install-script>

**Comment by ahoneybun** [comment]
I rebooted and the webcam was there in lsusb and was able to use it with Cheese.

**Comment by ahoneybun** [comment]
Then I suspended for a bit and resumed to find the laptop in Airplane Mode and the webcam was gone again.

**Comment by jackpot51** [comment]
I believe the webcam will work better with the latest firmware. I still haven't figured out the camera toggle hotkey.
