### ISSUE TITLE
Q: Is `SOC_INTEL_ALDERLAKE_PCH_S` compatible with i7-12650H?

### ISSUE THREAD

**Issue by Kreyren** [system76/coreboot#236]
Hey, i am trying to make a coreboot for https://www.tulparnotebook.de/t-serie-t5-v-23-2 which seems to be an identical system to system76 addw3 just with different CPU configuration -> Is the  `SOC_INTEL_ALDERLAKE_PCH_S` compatible with i7-12650H or should i use different option?

**Comment by crawfxrd** [comment]
S/HX CPUs use PCH-S, H/U CPUs use PCH-P.
