### ISSUE TITLE
About commit frequency 

### ISSUE THREAD

**Issue by hwpplayer1** [system76/coreboot#25]
Hi System76!

I'm following coreboot source code for a few days. And getting updates more than one time in a day. I wanted to learn how you work, and do you have any other policy about your own hardware.

Thanks, happy hacking!

**Comment by crawfxrd** [comment]
> And getting updates more than one time in a day.

That is to be expected. Like all our active projects, commits are regularly pushed to development branches and merged (in this case, to the `system76` branch) when they are sufficiently developed. Occasionally, upstream is merged in to keep us up to date with their development.

@jackpot51  is currently working on supported AMD Ryzen 3000 CPUs, so you are likely to see a lot of activity in the `matisse` branch.

> I wanted to learn how you work, and do you have any other policy about your own hardware.

Can you elaborate?

**Comment by hwpplayer1** [comment]
> > And getting updates more than one time in a day.
> 
> That is to be expected. Like all our active projects, commits are regularly pushed to development branches and merged (in this case, to the `system76` branch) when they are sufficiently developed. Occasionally, upstream is merged in to keep us up to date with their development.
> 
> @jackpot51 is currently working on supporting AMD Ryzen 3000 CPUs, so you are likely to see a lot of activity in the `matisse` branch.
> 
> > I wanted to learn how you work, and do you have any other policy about your own hardware.
> 
> Can you elaborate?

Thanks for your reply, since the software is free but hardware is maintained by System76, so i thought there was a code of conduct or similar principles for a contributor/committer.

I'll follow the ```matisse`` as soon as possible.

Thanks...

**Comment by crawfxrd** [comment]
You can view coreboot's code of conduct [here](https://doc.coreboot.org/community/code_of_conduct.html).

You can view coreboot's guideline for commits [here](https://doc.coreboot.org/tutorial/part2.html#step-4a-use-the-command-line-to-stage-and-submit-a-commit).

As for contributions to System76's fork, they will be handled at our discretion.

System76 does not maintain the hardware (in the sense we do not produce the hardware in-house and so are not responsible for any hardware revisions), which are provided by different companies.
