### ISSUE TITLE
Internal Testing

### ISSUE THREAD

**Issue by jackpot51** [system76/coreboot#4]
Flash Coreboot with UEFI on the following machines:

- [ ] Carl - galp2
- [ ] Emma - galp2
- [x] Harris - galp2
- [x] May - galp2
- [x] Katie - galp3
- [x] Louisa - galp3-b
- [x] Aaron - galp3-b
- [x] Alex - galp3-b
- [x] Ben C. - galp3-b
- [x] Joshua - galp3-c (13 inch)
- [x] Jeremy - galp3-c (14 inch)
- [x] Ben S. - darp5 - after dock testing

**Comment by jackpot51** [comment]
This is a tag identifying the version I am installing on these machines. https://github.com/system76/coreboot/releases/tag/internal

**Comment by jackpot51** [comment]
Update Coreboot with UEFI on the following machines to this tag: https://github.com/system76/coreboot/releases/tag/internal-2

- [ ] Carl - galp2
- [ ] Emma - galp2
- [ ] Harris - galp2
- [ ] May - galp2
- [ ] Katie - galp3
- [ ] Louisa - galp3-b
- [ ] Aaron - galp3-b
- [ ] Alex - galp3-b
- [ ] Ben C. - galp3-b
- [ ] Joshua - galp3-c (13 inch)
- [ ] Jeremy - galp3-c (14 inch)
- [ ] Ben S. - darp5 - after dock testing

**Comment by crawfxrd** [comment]
Do we need this issue?

**Comment by leviport** [comment]
Probably not
