### ISSUE TITLE
Xen fails to boot on lemp10 firmware

### ISSUE THREAD

**Issue by lead4good** [system76/coreboot#41]
Booting qubes 4.0.3; xen 4.8.5 as well as qubes 4.1; xen 4.14 on the Clevo L141MU with system76 firmware flashed via the system76-firmware tool results in a xen panic at boot: *IO-APIC + timer doesn't work!*
See attached picture for detailed error message while run with apic_verbosity=debug

![IMG_20201207_084016](https://user-images.githubusercontent.com/1242489/101324057-e6cf5100-3869-11eb-9eee-77593b6b296e.jpg)

**Comment by jacobgkau** [comment]
lemp10 is L140MU and not L141MU. It looks like the only difference should be the color, but someone will need to check whether this issue also occurs on officially-supported hardware since we can't know if other Clevo variations have obscure or even undocumented differences. (Different batches of the same code can also have different bills of materials; we are only able to guarantee what we sell since we don't control anything else.)

**Comment by lead4good** [comment]
@jacobgkau thanks for your quick response. I am very sure that this is not due to different hardware. You can check for yourself by trying to boot qubes 4.0.3 stable or qubes 4.1 alpha on a real lemp10. My lay guess is that this issue is due to the S0ix support that the lemp10 firmware started supporting. At least acpi related code has seen a lot of commits. Why xen cannot find the 8254 timer I can not explain though. I've read somewhere that the timer gets disabled in cpu sleep states, but I don't think this is the case during boot.

**Comment by lead4good** [comment]
@jackpot51 
Is there a specific reason why `USE_LEGACY_8254_TIMER` was removed from the lemp10 config? The lemp9 still has it: https://github.com/system76/coreboot/blob/5fbdab4ddbe99de0a9e74f50440e57246c04c1f7/src/mainboard/system76/lemp9/Kconfig#L24

**Comment by crawfxrd** [comment]
GRUB no longer needs the workaround [\[1\]](https://review.coreboot.org/c/coreboot/+/45960). However, it looks like 9elements is adding it back for other reasons [\[2\]](https://review.coreboot.org/c/coreboot/+/34709).

**Comment by jackpot51** [comment]
@lead4good we do not provide firmware support for non-System76 machines
