### ISSUE TITLE
Status of Renoir and Matisse 

### ISSUE THREAD

**Issue by n00b7** [system76/coreboot#53]
I have a Gigabyte Aorus Pro X570 WiFi I would like coreboot on, and heard that it was being ported to newer AMD Chipsets, but I don’t see any definitions in the code for anything other than gen 1(Picasso) boards

**Comment by crawfxrd** [comment]
Development for Matisse has been stalled. @jackpot51 would have to give more information on the state of the `matisse` branch.

There has been work upstream to add support for Cezanne.

**Comment by n00b7** [comment]
Are there any tools to extract the Platform Security Processor Pubkey and init binaries

**Comment by jackpot51** [comment]
Gigabyte has never provided the information required (mainly schematics) for porting coreboot, even on supported SOC's like the Intel CPUs we already support on laptops.

Renoir is being worked on by the chromebook team. The FSP-style wrapper of AGESA is not shared with us yet.

Matisse has not seen enough support from AMD for us to get what we need, an FSP-style wrapper of AGESA.
